language: python
python:
- "3.7-dev"
install:
- docker pull alpine
- docker pull python
- docker pull python:alpine
- docker pull python:slim
script:
- make
before_deploy:
- docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
deploy:
- provider: script
  script: make push
  on:
    tags: true
    repo: amancevice/docker-pandas
