version: '3'
services:
  alpine:
    build:
      context: alpine
      args:
        PANDAS_VERSION: ${PANDAS_VERSION}
    image: amancevice/pandas:${PANDAS_VERSION}-alpine
  debian:
    build:
      context: .
      args:
        PANDAS_VERSION: ${PANDAS_VERSION}
    image: amancevice/pandas:${PANDAS_VERSION}
  jupyter:
    build:
      context: jupyter
      args:
        PANDAS_VERSION: ${PANDAS_VERSION}
    image: amancevice/pandas:${PANDAS_VERSION}-jupyter
    ports:
      - 8888:8888
  slim:
    build: slim
    image: amancevice/pandas:${PANDAS_VERSION}-slim
