version: '3'
services:
  jupyter:
    build: Jupyter
    image: amancevice/pandas:jupyter
    ports:
      - 8888:8888
  latest:
    build: Python3
    image: amancevice/pandas:latest
  alpine:
    build:
      context: Python3
      dockerfile: Dockerfile.alpine
    image: amancevice/pandas:alpine
  slim:
    build:
      context: Python3
      dockerfile: Dockerfile.slim
    image: amancevice/pandas:slim
